![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np

In [3]:
np.__version__

'2.2.5'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [5]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [3]:
a = np.ones((3,3),dtype=bool)
print(a)

b = np.full((3,3), True)
print(b)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [ ]:
print(my_array)



[0 1 2 3 4 5 6 7 8 9]


In [8]:
for n in my_array:
    if n%2 == 1:
        print(n)

1
3
5
7
9


In [12]:
mask = (my_array % 2) == 1
impares = my_array[mask]
print(impares)

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [15]:
new_array = my_array.copy()
new_array[new_array % 2 == 1] = -1
print(new_array)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [16]:
nueva_array = np.where(my_array%2 == 1, -1, my_array)
print(nueva_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [23]:
otro_array = my_array.reshape((2, 5))
print(otro_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [35]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#print(a)
#print(b)
c = np.concatenate((a,b), axis=0)
print(c)



[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [36]:
d = np.concatenate((a,b), axis=1)
print(d)



[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

interseccion = np.intersect1d(a,b)
print(interseccion)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [40]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [51]:
my_array2 = np.arange(0,10)
print(my_array2)
my_array2 * 10
my_array2[0]
my_array2[-1]
my_array2[1:8]

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7])

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [52]:
my_matrix = ([
    [1,2,3],
    [3,4,5],
    [6,7,8]
])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [58]:
secuencia = np.arange(1,50)
print(secuencia)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [64]:
secuencia2 = np.arange(4.0,1.0,-0.25)
print(secuencia2)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [ ]:
import matplotlib.pyplot as plt

imagen = plt.imread() #("./dondelechestestelaimagen/numpy.png")
print(type(imagen))
print(imagen.shape)

plt.imshow(imagen)

FileNotFoundError: [Errno 2] No such file or directory: 'numpy.png'

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [66]:
m = np.array([
    [10],
    [20],
    [30],
    [40],
])
m2 = m.reshape(2,2)
print(m2)

[[10 20]
 [30 40]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [68]:
random = np.random.randint(0,10, size=(4,5,3))
print(random)

[[[6 0 7]
  [6 8 4]
  [9 6 5]
  [9 9 0]
  [8 3 5]]

 [[9 5 0]
  [2 0 6]
  [9 7 7]
  [2 4 4]
  [0 6 7]]

 [[8 0 5]
  [3 2 6]
  [3 5 4]
  [9 0 4]
  [0 4 5]]

 [[7 8 0]
  [5 3 1]
  [6 6 8]
  [9 2 1]
  [2 5 3]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [71]:
h = np.full((10,1), False)
print(h)
h2 = h.reshape(2,5)
print(h2)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [72]:
x =np.random.randint(10, 20, size = (5,2,6))
print(x)

[[[16 10 10 19 17 18]
  [14 12 15 19 17 14]]

 [[15 12 14 19 11 17]
  [15 15 16 10 15 11]]

 [[11 12 16 13 13 12]
  [18 12 19 17 12 19]]

 [[11 10 19 11 18 19]
  [14 13 19 13 14 13]]

 [[15 16 19 18 13 16]
  [10 12 12 17 18 18]]]
